### ISSUE TITLE
Group source code by course

### ISSUE THREAD

**Issue by zijieku** [wadefagen/coursera#9]
Please group source codes by Courses. 

repo
|-- Object-Oriented Data Structures in C++ 
|     + ...
|-- Ordered Data Structure
|    + ...
+- Unordered Data Structure
     + ...

Thank you.

**Comment by echuber2** [comment]
We might be able to do this, but I'm not sure if we should, because it will no doubt upset or confuse some people who've already got a terminal window open to one of the nested directories when they do "git pull". We'll have to tell them to be sure to go to the root first:

```
cd `git rev-parse --show-toplevel`
git stash
git pull
```

We would also have to update a lot of the Makefiles to point to the correct relative path of the master makefile.

In the meantime, you can organize the folders for yourself while maintaining your links to the current locations using symlinks. For example:

```bash
#!/bin/bash

EXAMPLES_TOP_DIR=$(git rev-parse --show-toplevel)
COURSE_1_SUBDIR=courses/cs-fundamentals-1
COURSE_2_SUBDIR=courses/cs-fundamentals-2
COURSE_3_SUBDIR=courses/cs-fundamentals-3

# go to top directory
cd ${EXAMPLES_TOP_DIR}

# make course directories for organization
mkdir -p ${EXAMPLES_TOP_DIR}/${COURSE_1_SUBDIR}
mkdir -p ${EXAMPLES_TOP_DIR}/${COURSE_2_SUBDIR}
mkdir -p ${EXAMPLES_TOP_DIR}/${COURSE_3_SUBDIR}

# make symbolic links to the examples underneath the course directories
ln -s ${EXAMPLES_TOP_DIR}/cpp-ctor ${EXAMPLES_TOP_DIR}/${COURSE_1_SUBDIR}/cpp-ctor
# ...
# ...
```

(You'd need to finish adding lines at the bottom to make links for all the examples you want.) This has the benefit of leaving the existing directory structure in-place for the sake of git updates.

**Comment by zijieku** [comment]
Sure. Sounds good. Thanks!

**Comment by zijieku** [comment]
Sure. Sounds good. Thanks!

**Comment by BrianLeip** [comment]
I'll second this!  Would be great to have the folders organized by section / course
